### ISSUE TITLE
Unsupported getMoreResults() breaks Eclipse Data Tooling

### ISSUE THREAD

**Issue by WalternativE** [crate/crate-jdbc#193]
Hello!

I've been playing around with CrateDB for the last couple of days and encountered a problem when using the Eclipse Data Tooling (especially the SQL Scratchpad). Unfortunately Eclipse just logs the Exception to the output and carries on to use the function until a boolean value is returned (which never happens). I understand that this is an Eclipse problem as it doesn't react appropriately to the exceptional behavior but I would be very interested into the reason for not implementing getMoreResults().

I assume there is a reason, as the behavior is unit tested and the implementation explicitly differs from the official postgres jdbc driver implementation.

To use the Data Tooling I cloned the repo and simply copied the postgres implementation of getMoreResults() which worked well for me - but I only used it for some data definition and some simple queries which is trivial compared to extensive usage.

Thank you very much in advance for answering my question.

Regards
Gregor

**Comment by chaudum** [comment]
Hi @WalternativE ,

Thanks for reporting! You're right, Eclipse does not handle the exception correctly in the first place. HOWEVER, there is no reason why CrateDB JDBC does not implement the method, also. I cannot remember by hard, why we did not implement this method yet, however, we will have a another look and let you know! We'll probably implement it as in Postgres JDBC.

**Comment by WalternativE** [comment]
Hi @chaudum,

thanks for the response. I'm looking forward to seeing the new version :) Until then I'll just use my patched version. Maybe I come around to write an issue for the Eclipse subproject as well, can't imagine that this is the only case where someone has problems with this exception handling behavior.

Regards

**Comment by chaudum** [comment]
@WalternativE we've implemented getMoreResults() they way original pgjdbc does. it will be available with the next release.

**Comment by WalternativE** [comment]
Thank you very much!

**Comment by joalmjoalm** [comment]
Hi 

Squirrel works fine with Crate 1.0.2 and jdbc standalone driver 2.1.4 but I dont get Streamsets to work with Crate 1.0.2 with the standalone driver 2.1.4. I have tested w Streamsets 2.2.1.0 and 1.6.0.0.

Any special config /jdbc properties needed or any fix in the jdbc 2.1.4 ?

get error: JDBC_00 - Cannot connect to specified database: com.streamsets.pipeline.api.StageException: JDBC_06 - Failed to initialize connection pool: io.crate.shade.org.postgresql.util.PSQLException: ERROR: SQLParseException: line 1:13: no viable alternative at input 'CHARACTERISTICS'

Jonas

**Comment by chaudum** [comment]
@WalternativE the fix has been released with `2.1.4` https://github.com/crate/crate-jdbc/blob/master/CHANGES.txt#L15-L21
